import { useEffect,useMemo,useRef,useState,type FormEvent,type ReactNode } from 'react';
import { Link,NavLink,Route,Routes,useLocation,useNavigate,useNavigationType,useParams,useSearchParams } from 'react-router-dom';
import { ArrowLeft,Bookmark,CalendarDays,Check,ChevronDown,ChevronLeft,ChevronRight,Clapperboard,Clock3,Compass,Film,Heart,Home as HomeIcon,Info,Library,LoaderCircle,Menu,Play,RefreshCw,Search,SlidersHorizontal,Sparkles,Star,Users,WifiOff,X } from 'lucide-react';
import { useGetCatalogQuery,useGetContinueQuery,useGetEpisodeQuery,useGetFavoriteQuery,useGetFavoritesQuery,useGetHealthQuery,useGetLocalMoviesQuery,useGetMovieQuery,useGetSyncQuery,useGetTaxonomyQuery,useImportMovieMutation,useSaveProgressMutation,useSearchCatalogQuery,useSetFavoriteMutation,useStartSyncMutation } from './api';
import type { CatalogKind,CatalogQuery,Episode,Movie,MovieList,TaxonomyItem } from './types';

const listLabels:Record<string,string>={'phim-moi-cap-nhat':'Mới cập nhật','phim-le':'Phim lẻ','phim-bo':'Phim bộ','dang-chieu':'Đang chiếu','4k':'Phim 4K','long-tieng':'Lồng tiếng','thuyet-minh':'Thuyết minh','subteam':'Subteam'};
const image=(movie:Movie,wide=false)=>wide?(movie.thumbUrl||movie.posterUrl):(movie.posterUrl||movie.thumbUrl);
const clean=(html:string|null)=>html?html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim():'';
const scrollPositions=new Map<string,number>();

function NavigationEffects(){const location=useLocation();const type=useNavigationType();useEffect(()=>{const y=type==='POP'?(scrollPositions.get(location.key)??0):0;requestAnimationFrame(()=>scrollTo({top:y}));return()=>{scrollPositions.set(location.key,scrollY)}},[location.key]);return null}
function Logo(){return <Link className="logo" to="/" aria-label="BảoNhànCinema - Trang chủ"><span><Clapperboard/></span><b>BảoNhànCinema</b></Link>}

function Header(){const navigate=useNavigate();const location=useLocation();const [menuOpen,setMenuOpen]=useState(false);const [q,setQ]=useState('');useEffect(()=>setMenuOpen(false),[location.pathname,location.search]);useEffect(()=>{if(!menuOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenuOpen(false)};document.body.classList.add('menu-open');addEventListener('keydown',close);return()=>{document.body.classList.remove('menu-open');removeEventListener('keydown',close)}},[menuOpen]);const submit=(event:FormEvent)=>{event.preventDefault();const value=q.trim();if(value)navigate(`/search?q=${encodeURIComponent(value)}`)};return <header className="app-header"><Logo/><button className={menuOpen?'nav-backdrop open':'nav-backdrop'} onClick={()=>setMenuOpen(false)} aria-label="Đóng menu"/><nav className={menuOpen?'main-nav open':'main-nav'} aria-label="Điều hướng chính"><NavLink to="/" end><HomeIcon/>Trang chủ</NavLink><NavLink to="/browse/list/phim-le"><Film/>Phim lẻ</NavLink><NavLink to="/browse/list/phim-bo"><Clapperboard/>Phim bộ</NavLink><NavLink to="/browse/list/dang-chieu"><Compass/>Khám phá</NavLink><NavLink to="/library"><Library/>Thư viện</NavLink><button className="nav-close icon-button" onClick={()=>setMenuOpen(false)} aria-label="Đóng menu"><X/></button></nav><div className="header-actions"><form className="header-search" onSubmit={submit}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm phim..." aria-label="Tìm kiếm phim"/></form><Link className="icon-button mobile-search" to="/search" aria-label="Tìm kiếm"><Search/></Link><Link className="icon-button desktop-icon" to="/people" title="Diễn viên"><Users/></Link><button className="icon-button menu-button" onClick={()=>setMenuOpen(true)} aria-label="Mở menu" aria-expanded={menuOpen}><Menu/></button></div></header>}
function Shell({children,flush=false}:{children:ReactNode;flush?:boolean}){return <><NavigationEffects/><Header/><main className={flush?'flush':''}>{children}</main><footer><Logo/><p>Rạp phim cá nhân trên mạng nội bộ</p><div><Link to="/local">Kho local</Link><Link to="/people">Diễn viên</Link><Link to="/showtimes">Lịch phát hành</Link></div></footer></>}

function MovieCard({movie,rank}:{movie:Movie;rank?:number}){return <Link className="movie-card" to={`/movie/${movie.slug}`} aria-label={`Xem chi tiết ${movie.name}`}>{rank&&<span className="rank">{rank}</span>}<div className="poster"><img src={image(movie)||'/poster-placeholder.svg'} alt={movie.name} loading="lazy"/><span className="card-play"><Play fill="currentColor"/></span><div className="badges">{movie.quality&&<b>{movie.quality}</b>}{movie.language&&<b>{movie.language.split('+')[0].trim()}</b>}</div></div><h3>{movie.name}</h3><p><span>{movie.year||'Đang cập nhật'}</span>{movie.rating?<><Star fill="currentColor"/>{movie.rating.toFixed(1)}</>:null}</p></Link>}
function MovieRow({title,items,to,ranked=false}:{title:string;items:Movie[];to:string;ranked?:boolean}){if(!items.length)return null;return <section className="shelf"><div className="section-heading"><div><span>Danh sách chọn lọc</span><h2>{title}</h2></div><Link to={to}>Xem tất cả<ChevronRight/></Link></div><div className={ranked?'movie-row ranked':'movie-row'}>{items.map((movie,index)=><MovieCard key={`${movie.slug}-${index}`} movie={movie} rank={ranked?index+1:undefined}/>)}</div></section>}
function SkeletonGrid({count=12}:{count?:number}){return <div className="movie-grid">{Array.from({length:count},(_,i)=><div className="skeleton-card" key={i}><i/><b/><span/></div>)}</div>}
function ErrorState({onRetry,message='Không thể tải dữ liệu lúc này.'}:{onRetry?:()=>void;message?:string}){return <div className="state-panel"><WifiOff/><h2>Kết nối bị gián đoạn</h2><p>{message}</p>{onRetry&&<button className="button secondary" onClick={onRetry}><RefreshCw/>Thử lại</button>}</div>}
function EmptyState({title='Chưa có nội dung',message='Hãy thử thay đổi bộ lọc hoặc quay lại sau.'}:{title?:string;message?:string}){return <div className="state-panel"><Film/><h2>{title}</h2><p>{message}</p></div>}

function SyncStatus(){const health=useGetHealthQuery(undefined,{pollingInterval:15000});const {data}=useGetSyncQuery(undefined,{pollingInterval:3000,skip:health.isError});const [start,{isLoading}]=useStartSyncMutation();const working=data?.status==='running';const offline=health.isError;return <div className={offline?'sync-status offline':'sync-status'}><span className="sync-icon">{offline?<WifiOff/>:<RefreshCw className={working?'spin':''}/>}</span><div><b>{offline?'Backend đang ngoại tuyến':working?'Đang cập nhật thư viện':'Dữ liệu local'}</b><small>{offline?'Kiểm tra dịch vụ API tại cổng 4000':working?`${data?.processed??0} phim · trang ${data?.page??0}/${data?.totalPages??'?'}`:`${data?.processed??0} phim đã đồng bộ`}</small></div><button disabled={offline||working||isLoading} onClick={()=>start({pages:3})}>{working?'Đang chạy':'Đồng bộ'}</button></div>}

function Home(){const home=useGetCatalogQuery({kind:'home',page:1,limit:24});const series=useGetCatalogQuery({kind:'list',value:'phim-bo',page:1,limit:12});const movies=useGetCatalogQuery({kind:'list',value:'phim-le',page:1,limit:12});const ultra=useGetCatalogQuery({kind:'list',value:'4k',page:1,limit:12});const featured=home.data?.items[0];const top=useMemo(()=>[...(home.data?.items??[])].sort((a,b)=>(b.rating??0)-(a.rating??0)).slice(0,10),[home.data]);if(home.isError&&!featured)return <Shell><div className="page-container page-top"><ErrorState onRetry={home.refetch}/></div></Shell>;return <Shell flush>{featured?<section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(8,8,10,.98) 3%,rgba(8,8,10,.72) 46%,rgba(8,8,10,.16) 76%),linear-gradient(0deg,#09090b 0%,transparent 38%),url("${image(featured,true)}")`}}><div className="hero-copy"><span className="eyebrow"><Sparkles/>Mới trên Local Cinema</span><h1>{featured.name}</h1><p className="origin-name">{featured.originName}</p><MovieMeta movie={featured}/><p className="description">{clean(featured.description)||`Khám phá ${featured.name} cùng thư viện phim được cập nhật liên tục.`}</p><div className="actions"><Link className="button primary" to={`/movie/${featured.slug}`}><Play fill="currentColor"/>Xem ngay</Link><Link className="button secondary" to={`/movie/${featured.slug}`}><Info/>Chi tiết</Link></div></div></section>:<div className="hero-skeleton"/>}<div className="page-container home-content"><SyncStatus/>{home.isLoading?<SkeletonGrid/>:<MovieRow title="Mới cập nhật" items={home.data?.items??[]} to="/browse/list/phim-moi-cap-nhat"/>}<MovieRow title="Top đánh giá" items={top} to="/browse/list/phim-moi-cap-nhat?sort=rating" ranked/><MovieRow title="Phim bộ đáng xem" items={series.data?.items??[]} to="/browse/list/phim-bo"/><MovieRow title="Phim lẻ mới" items={movies.data?.items??[]} to="/browse/list/phim-le"/><MovieRow title="Trải nghiệm 4K" items={ultra.data?.items??[]} to="/browse/list/4k"/></div></Shell>}
function MovieMeta({movie}:{movie:Movie}){return <div className="meta">{movie.rating&&<span className="rating"><Star fill="currentColor"/>{movie.rating.toFixed(1)}</span>}<span>{movie.year}</span>{movie.quality&&<span className="quality">{movie.quality}</span>}<span>{movie.type==='series'||movie.type==='tv'?'Phim bộ':'Phim lẻ'}</span>{movie.duration&&<span>{movie.duration} phút</span>}</div>}

function useCatalogParams(){const [searchParams,setSearchParams]=useSearchParams();const page=Math.max(1,Number(searchParams.get('page')??1));const filters={page,limit:24,year:searchParams.get('year')||undefined,country:searchParams.get('country')||undefined,category:searchParams.get('category')||undefined,type:searchParams.get('type')||undefined,status:searchParams.get('status')||undefined};const update=(key:string,value:string)=>{const next=new URLSearchParams(searchParams);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.set('page','1');setSearchParams(next)};return {searchParams,page,filters,update}}
function Browse(){const {kind='list',value='phim-moi-cap-nhat'}=useParams();const safeKind=(['list','genre','country','year','code'].includes(kind)?kind:'list') as CatalogKind;const {page,filters,update}=useCatalogParams();const query:CatalogQuery={kind:safeKind,value,...filters};if(safeKind==='year')delete query.year;if(safeKind==='country')delete query.country;if(safeKind==='genre')delete query.category;const result=useGetCatalogQuery(query);const title=safeKind==='list'?(listLabels[value]??'Khám phá phim'):safeKind==='genre'?`Thể loại: ${humanize(value)}`:safeKind==='country'?`Phim ${humanize(value)}`:safeKind==='year'?`Phim năm ${value}`:`Lịch phát hành ${decodeURIComponent(value)}`;return <Shell><div className="page-container page-top"><Breadcrumb items={[['Trang chủ','/'],['Khám phá','/browse/list/dang-chieu'],[title,'']]}/><div className="page-title"><div><span>Kho phim VSMOV</span><h1>{title}</h1><p>{result.data?.pagination.totalItems??0} nội dung phù hợp</p></div></div><FilterBar filters={filters} update={update}/>{result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState onRetry={result.refetch}/>:result.data?.items.length?<><div className="movie-grid">{result.data.items.map((movie,index)=><MovieCard key={`${movie.slug}-${index}`} movie={movie}/>)}</div><Pagination current={page} total={result.data.pagination.totalPages} onChange={value=>update('page',String(value))}/></>:<EmptyState/>}</div></Shell>}
function FilterBar({filters,update}:{filters:Record<string,any>;update:(key:string,value:string)=>void}){const genres=useGetTaxonomyQuery('genres');const countries=useGetTaxonomyQuery('countries');const years=useGetTaxonomyQuery('years');return <div className="filter-bar"><span className="filter-label"><SlidersHorizontal/>Bộ lọc</span><SelectFilter label="Thể loại" value={filters.category??''} items={genres.data?.items??[]} onChange={v=>update('category',v)}/><SelectFilter label="Quốc gia" value={filters.country??''} items={countries.data?.items??[]} onChange={v=>update('country',v)}/><SelectFilter label="Năm" value={filters.year??''} items={(years.data?.items??[]).slice(0,50)} onChange={v=>update('year',v)}/><SelectFilter label="Định dạng" value={filters.type??''} items={[{id:'single',name:'Phim lẻ',slug:'single',thumbUrl:null},{id:'series',name:'Phim bộ',slug:'series',thumbUrl:null},{id:'hoathinh',name:'Hoạt hình',slug:'hoathinh',thumbUrl:null},{id:'tvshows',name:'TV Shows',slug:'tvshows',thumbUrl:null}]} onChange={v=>update('type',v)}/><SelectFilter label="Trạng thái" value={filters.status??''} items={[{id:'ongoing',name:'Đang chiếu',slug:'ongoing',thumbUrl:null},{id:'completed',name:'Hoàn thành',slug:'completed',thumbUrl:null},{id:'trailer',name:'Trailer',slug:'trailer',thumbUrl:null}]} onChange={v=>update('status',v)}/></div>}
function SelectFilter({label,value,items,onChange}:{label:string;value:string;items:TaxonomyItem[];onChange:(value:string)=>void}){return <label className="select-control"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Tất cả</option>{items.map(item=><option key={`${item.id}-${item.slug}`} value={item.slug}>{item.name}</option>)}</select><ChevronDown/></label>}
function Pagination({current,total,onChange}:{current:number;total:number;onChange:(page:number)=>void}){if(total<=1)return null;const pages=Array.from(new Set([1,current-1,current,current+1,total])).filter(p=>p>=1&&p<=total).sort((a,b)=>a-b);return <nav className="pagination" aria-label="Phân trang"><button disabled={current<=1} onClick={()=>onChange(current-1)} aria-label="Trang trước"><ChevronLeft/></button>{pages.map((page,index)=><span key={page}>{index>0&&page-pages[index-1]>1?<i>…</i>:null}<button className={page===current?'active':''} onClick={()=>onChange(page)}>{page}</button></span>)}<button disabled={current>=total} onClick={()=>onChange(current+1)} aria-label="Trang sau"><ChevronRight/></button></nav>}

function SearchPage(){const [params,setParams]=useSearchParams();const query=params.get('q')??'';const page=Math.max(1,Number(params.get('page')??1));const [draft,setDraft]=useState(query);useEffect(()=>setDraft(query),[query]);const result=useSearchCatalogQuery({q:query,page,limit:24},{skip:query.length<2});const submit=(event:FormEvent)=>{event.preventDefault();const value=draft.trim();setParams(value?{q:value,page:'1'}:{})};return <Shell><div className="page-container page-top"><form className="search-hero" onSubmit={submit}><Search/><input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Tìm theo tên phim..."/><button className="button primary">Tìm kiếm</button></form><div className="page-title compact"><div><span>Tìm kiếm toàn bộ VSMOV</span><h1>{query?`Kết quả cho “${query}”`:'Bạn muốn xem gì?'}</h1><p>{result.data?.pagination.totalItems??0} kết quả</p></div></div>{query.length<2?<EmptyState title="Nhập ít nhất 2 ký tự" message="Tìm theo tên tiếng Việt hoặc tên gốc của phim."/>:result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState onRetry={result.refetch}/>:result.data?.items.length?<><div className="movie-grid">{result.data.items.map((movie,index)=><MovieCard key={`${movie.slug}-${index}`} movie={movie}/>)}</div><Pagination current={page} total={result.data.pagination.totalPages} onChange={next=>setParams({q:query,page:String(next)})}/></>:<EmptyState title="Không tìm thấy phim" message="Thử từ khóa ngắn hơn hoặc kiểm tra cách viết."/>}</div></Shell>}

function Detail(){const {slug=''}=useParams();const result=useGetMovieQuery(slug);if(result.isLoading)return <Shell><div className="full-loader"><LoaderCircle className="spin"/></div></Shell>;if(result.isError||!result.data?.movie)return <Shell><div className="page-container page-top"><ErrorState onRetry={result.refetch} message="Không thể mở thông tin phim này."/></div></Shell>;const movie=result.data.movie;const first=movie.episodes?.[0];return <Shell flush><section className="detail-hero" style={{backgroundImage:`linear-gradient(90deg,#09090b 3%,rgba(9,9,11,.78) 50%,rgba(9,9,11,.18)),linear-gradient(0deg,#09090b 0%,transparent 45%),url("${image(movie,true)}")`}}><div className="detail-inner"><Breadcrumb items={[['Trang chủ','/'],['Khám phá','/browse/list/phim-moi-cap-nhat'],[movie.name,'']]}/><div className="detail-copy"><span className="eyebrow">{movie.type==='series'?'Original series':'Feature film'}</span><h1>{movie.name}</h1><p className="origin-name">{movie.originName}</p><MovieMeta movie={movie}/><p className="description">{clean(movie.description)||'Nội dung đang được cập nhật.'}</p><div className="actions">{first?<Link className="button primary" to={`/watch/${movie.slug}/${first.id}`}><Play fill="currentColor"/>Xem ngay</Link>:<button className="button primary" disabled><Play/>Chưa có tập</button>}<FavoriteButton movieId={movie.id}/></div></div></div></section><div className="page-container detail-content"><EpisodeList movie={movie}/><section className="detail-info"><div><span className="section-kicker">Thông tin phim</span><h2>Chi tiết</h2><InfoRow label="Thể loại" value={movie.genres.join(', ')}/><InfoRow label="Quốc gia" value={movie.countries.join(', ')}/><InfoRow label="Đạo diễn" value={movie.directors.join(', ')}/><InfoRow label="Ngôn ngữ" value={movie.language??''}/></div><div><span className="section-kicker">Dàn cast</span><h2>Diễn viên</h2><p>{movie.actors.slice(0,16).join(', ')||'Đang cập nhật'}</p></div></section></div></Shell>}
function FavoriteButton({movieId}:{movieId:number}){const favorite=useGetFavoriteQuery(movieId);const [setFavorite,{isLoading}]=useSetFavoriteMutation();const active=Boolean(favorite.data?.favorite);const pathname=useLocation().pathname;const slug=pathname.startsWith('/movie/')?decodeURIComponent(pathname.slice(7)):'';return <><button disabled={isLoading} className={active?'button secondary active':'button secondary'} onClick={()=>setFavorite({movieId,enabled:!active})}><Heart fill={active?'currentColor':'none'}/>{active?'Đã thêm':'Danh sách của tôi'}</button>{slug&&<ImportButton slug={slug}/>}</>}
function ImportButton({slug}:{slug:string}){const [run,{isLoading,isSuccess,isError}]=useImportMovieMutation();return <button className="button secondary compact-action" disabled={isLoading} onClick={()=>run(slug)} title="Tải lại metadata và nguồn phát từ VSMOV"><RefreshCw className={isLoading?'spin':''}/>{isLoading?'Đang cập nhật':isSuccess?'Đã cập nhật':isError?'Thử lại':'Cập nhật nguồn'}</button>}
function EpisodeList({movie}:{movie:Movie}){const groups=useMemo(()=>Object.entries((movie.episodes??[]).reduce<Record<string,Episode[]>>((all,episode)=>{(all[episode.serverName]??=[]).push(episode);return all},{})),[movie.episodes]);return <section className="episodes"><div className="section-heading"><div><span>Nguồn phát</span><h2>{movie.type==='series'?'Danh sách tập':'Phát phim'}</h2></div><p>{movie.episodes?.length??0} tập</p></div>{groups.length?groups.map(([server,episodes])=><div className="server-group" key={server}><h3>{server.trim()}</h3><div className="episode-grid">{episodes.map(episode=><Link key={episode.id} to={`/watch/${movie.slug}/${episode.id}`}><Play/>{episode.name}</Link>)}</div></div>):<EmptyState title="Chưa có nguồn phát" message="VSMOV chưa cung cấp tập phim cho nội dung này."/>}</section>}
function InfoRow({label,value}:{label:string;value:string}){return <p className="info-row"><b>{label}</b><span>{value||'Đang cập nhật'}</span></p>}

function VideoPlayer({episode,title}:{episode:Episode;title:string}){
  const videoRef=useRef<HTMLVideoElement>(null);
  const [fallback,setFallback]=useState(!episode.m3u8Url);
  useEffect(()=>setFallback(!episode.m3u8Url),[episode.id,episode.m3u8Url]);
  useEffect(()=>{
    if(fallback)return;
    const video=videoRef.current;
    if(!video||!episode.m3u8Url)return;
    const cleanCues=()=>Array.from(video.textTracks).forEach(track=>Array.from(track.cues??[]).forEach(cue=>{
      if('text' in cue)cue.text=String(cue.text).replace(/&lt;\/?i&gt;/gi,'').replace(/<\/?i>/gi,'');
    }));
    const interval=window.setInterval(cleanCues,1000);
    if(video.canPlayType('application/vnd.apple.mpegurl')){
      video.src=episode.m3u8Url;
      return()=>{window.clearInterval(interval);video.removeAttribute('src');video.load()};
    }
    let disposed=false;
    let destroy=()=>{};
    void import('hls.js').then(({default:Hls})=>{
      if(disposed)return;
      if(!Hls.isSupported()){setFallback(true);return}
      const hls=new Hls({enableWorker:true,lowLatencyMode:false});
      destroy=()=>hls.destroy();
      hls.loadSource(episode.m3u8Url!);
      hls.attachMedia(video);
      hls.on(Hls.Events.ERROR,(_event,data)=>{if(data.fatal)setFallback(true)});
    });
    return()=>{disposed=true;window.clearInterval(interval);destroy()};
  },[episode.id,episode.m3u8Url,fallback]);
  if(fallback)return <iframe src={episode.embedUrl} title={title} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen referrerPolicy="no-referrer"/>;
  return <video ref={videoRef} controls autoPlay playsInline title={title}/>;
}

function Watch(){const {slug='',episodeId=''}=useParams();const navigate=useNavigate();const result=useGetMovieQuery(slug);const [save]=useSaveProgressMutation();const started=useRef(Date.now());const movie=result.data?.movie;const episode=movie?.episodes?.find(item=>item.id===Number(episodeId));useEffect(()=>{if(!episode)return;save({episodeId:episode.id,position:1,duration:0});started.current=Date.now();return()=>{save({episodeId:episode.id,position:Math.max(1,Math.round((Date.now()-started.current)/1000)),duration:0})}},[episode?.id]);if(result.isLoading)return <div className="watch-loading"><LoaderCircle className="spin"/></div>;if(!movie||!episode)return <div className="watch-loading"><ErrorState message="Tập phim không tồn tại hoặc đã thay đổi."/></div>;const episodes=movie.episodes??[];const index=episodes.findIndex(item=>item.id===episode.id);return <div className="watch-page"><div className="watch-header"><Link to={`/movie/${slug}`}><ArrowLeft/><span>Quay lại</span></Link><div><b>{movie.name}</b><small>{episode.serverName.trim()} · {episode.name}</small></div><label><span>Tập</span><select value={episode.id} onChange={event=>navigate(`/watch/${slug}/${event.target.value}`)}>{episodes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><ChevronDown/></label></div><div className="player-frame"><VideoPlayer episode={episode} title={`${movie.name} - ${episode.name}`}/></div><div className="watch-footer">{index>0?<Link to={`/watch/${slug}/${episodes[index-1].id}`}><ChevronLeft/>Tập trước</Link>:<span/>}<button onClick={()=>save({episodeId:episode.id,position:0,duration:0,completed:true})}><Check/>Đã xem</button>{index<episodes.length-1?<Link to={`/watch/${slug}/${episodes[index+1].id}`}>Tập sau<ChevronRight/></Link>:<span/>}</div></div>}
function WatchRoute(){const {episodeId=''}=useParams();const id=Number(episodeId);const episode=useGetEpisodeQuery(id,{skip:!Number.isInteger(id)||id<1});if(episode.isLoading)return <div className="watch-loading"><LoaderCircle className="spin"/></div>;if(episode.isError)return <div className="watch-loading"><ErrorState message="Tập phim không tồn tại hoặc đã bị xóa khỏi kho local."/></div>;return <Watch/>}

function LibraryPage(){const favorites=useGetFavoritesQuery();const watching=useGetContinueQuery();return <Shell><div className="page-container page-top"><div className="page-title"><div><span>Cá nhân hóa</span><h1>Thư viện của tôi</h1><p>Nội dung đã lưu và đang xem dở trên thiết bị này</p></div><SyncStatus/></div><section className="library-section"><div className="section-heading"><div><span>Xem tiếp</span><h2>Đang xem</h2></div></div>{watching.data?.items.length?<div className="continue-grid">{watching.data.items.map(item=><Link key={item.episode_id} to={`/watch/${item.slug}/${item.episode_id}`}><img src={item.thumbUrl||'/poster-placeholder.svg'} alt=""/><div><Play fill="currentColor"/><span><b>{item.name}</b><small>Tập {item.episodeName}</small></span></div></Link>)}</div>:<EmptyState title="Chưa có phim đang xem" message="Phim bạn mở sẽ xuất hiện tại đây."/>}</section><section className="library-section"><div className="section-heading"><div><span>Bộ sưu tập</span><h2>Danh sách của tôi</h2></div></div>{favorites.isLoading?<SkeletonGrid count={6}/>:favorites.data?.items.length?<div className="movie-grid">{favorites.data.items.map(movie=><MovieCard key={movie.id} movie={movie}/>)}</div>:<EmptyState title="Danh sách đang trống" message="Nhấn “Danh sách của tôi” ở trang chi tiết để lưu phim."/>}</section></div></Shell>}
function LocalPage(){const [query,setQuery]=useState('');const result=useGetLocalMoviesQuery({q:query,sort:'rating'});return <Shell><div className="page-container page-top"><Breadcrumb items={[["Trang chủ","/"],["Thư viện","/library"],["Kho local",""]]}/><div className="page-title"><div><span>SQLite local</span><h1>Kho phim đã lưu</h1><p>{result.data?.pagination.totalItems??0} phim sẵn sàng phát trong mạng nội bộ</p></div><label className="inline-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Lọc kho local..."/></label></div>{result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState onRetry={result.refetch}/>:result.data?.items.length?<div className="movie-grid">{result.data.items.map(movie=><MovieCard key={movie.id} movie={movie}/>)}</div>:<EmptyState title="Kho local đang trống" message="Mở một phim từ VSMOV để hệ thống tự lưu metadata và nguồn phát."/>}</div></Shell>}

function PeoplePage(){const result=useGetTaxonomyQuery('actors');const [query,setQuery]=useState('');const people=useMemo(()=>{const normalized=query.trim().toLocaleLowerCase('vi');return (result.data?.items??[]).filter(item=>!normalized||item.name.toLocaleLowerCase('vi').includes(normalized)).slice(0,120)},[result.data,query]);return <Shell><div className="page-container page-top"><Breadcrumb items={[['Trang chủ','/'],['Diễn viên','']]}/><div className="page-title"><div><span>Kho dữ liệu VSMOV</span><h1>Diễn viên</h1><p>Khám phá những gương mặt trong thư viện</p></div><label className="inline-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Lọc diễn viên..."/></label></div>{result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState onRetry={result.refetch}/>:<div className="people-grid">{people.map(person=><article key={`${person.id}-${person.slug}`}><div>{person.thumbUrl?<img src={person.thumbUrl} alt={person.name} loading="lazy"/>:<Users/>}</div><h3>{person.name}</h3></article>)}</div>}</div></Shell>}
function ShowtimesPage(){const result=useGetTaxonomyQuery('codes');const [query,setQuery]=useState('');const codes=useMemo(()=>{const text=query.trim().toLowerCase();return (result.data?.items??[]).filter(item=>!text||item.name.toLowerCase().includes(text)).slice(-160).reverse()},[result.data,query]);return <Shell><div className="page-container page-top"><Breadcrumb items={[['Trang chủ','/'],['Lịch phát hành','']]}/><div className="page-title"><div><span>Showtimes code</span><h1>Lịch phát hành</h1><p>Chọn ngày để xem các phim liên quan</p></div><label className="inline-search"><CalendarDays/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ví dụ 2025..."/></label></div>{result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState onRetry={result.refetch}/>:<div className="code-grid">{codes.map(code=><Link key={`${code.id}-${code.slug}`} to={`/browse/code/${encodeURIComponent(code.slug)}`}><CalendarDays/><span>{code.name}</span><ChevronRight/></Link>)}</div>}</div></Shell>}

function Breadcrumb({items}:{items:[string,string][]}){return <nav className="breadcrumb" aria-label="Breadcrumb">{items.map(([label,to],index)=><span key={`${label}-${index}`}>{index>0&&<ChevronRight/>}{to?<Link to={to}>{label}</Link>:<b>{label}</b>}</span>)}</nav>}
function humanize(value:string){return decodeURIComponent(value).replace(/-/g,' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
function NotFound(){return <Shell><div className="page-container page-top"><div className="state-panel"><Compass/><h1>Trang không tồn tại</h1><p>Đường dẫn có thể đã thay đổi.</p><Link className="button primary" to="/">Về trang chủ</Link></div></div></Shell>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/browse/:kind/:value" element={<Browse/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/movie/:slug" element={<Detail/>}/><Route path="/watch/:slug/:episodeId" element={<WatchRoute/>}/><Route path="/library" element={<LibraryPage/>}/><Route path="/local" element={<LocalPage/>}/><Route path="/people" element={<PeoplePage/>}/><Route path="/showtimes" element={<ShowtimesPage/>}/><Route path="*" element={<NotFound/>}/></Routes>}
