CREATE TABLE IF NOT EXISTS movies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  provider_id TEXT,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  origin_name TEXT,
  description TEXT,
  type TEXT NOT NULL DEFAULT 'single',
  status TEXT,
  year INTEGER,
  duration TEXT,
  quality TEXT,
  language TEXT,
  poster_url TEXT,
  thumb_url TEXT,
  trailer_url TEXT,
  rating DOUBLE PRECISION,
  view_count INTEGER NOT NULL DEFAULT 0,
  tmdb_id TEXT,
  imdb_id TEXT,
  raw_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(provider, provider_id)
);
CREATE TABLE IF NOT EXISTS movie_genres (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(movie_id,name));
CREATE TABLE IF NOT EXISTS movie_countries (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(movie_id,name));
CREATE TABLE IF NOT EXISTS movie_people (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('actor','director')), name TEXT NOT NULL, UNIQUE(movie_id,kind,name));
CREATE TABLE IF NOT EXISTS episodes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, server_name TEXT NOT NULL, name TEXT NOT NULL, episode_number INTEGER, embed_url TEXT NOT NULL, m3u8_url TEXT, UNIQUE(movie_id,server_name,name));
CREATE TABLE IF NOT EXISTS watch_progress (device_id TEXT NOT NULL, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, episode_id INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE, position_seconds DOUBLE PRECISION NOT NULL DEFAULT 0, duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0, completed BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(device_id,episode_id));
CREATE TABLE IF NOT EXISTS favorites (device_id TEXT NOT NULL, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(device_id,movie_id));
CREATE TABLE IF NOT EXISTS sync_state (id INTEGER PRIMARY KEY CHECK(id=1), status TEXT NOT NULL DEFAULT 'idle', page INTEGER NOT NULL DEFAULT 0, total_pages INTEGER NOT NULL DEFAULT 0, processed INTEGER NOT NULL DEFAULT 0, error TEXT, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO sync_state(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
CREATE INDEX IF NOT EXISTS movies_updated_at_idx ON movies(updated_at DESC);
CREATE INDEX IF NOT EXISTS movie_people_kind_name_idx ON movie_people(kind,name);
CREATE INDEX IF NOT EXISTS watch_progress_device_updated_idx ON watch_progress(device_id,updated_at DESC);
