-- People + tìm kiếm không dấu.
-- Bản này khớp với migrateSchema() trong services/api/src/db.ts: API tự chạy DDL
-- lúc boot, file này để chạy tay trên Supabase hoặc để đọc lịch sử schema.

-- Tên phim đã bỏ dấu, ghi từ Node (xem services/api/src/text.ts).
-- Không dùng unaccent() của Postgres vì trên Supabase extension nằm ở schema
-- `extensions`, không IMMUTABLE nên không index được trực tiếp.
ALTER TABLE movies ADD COLUMN IF NOT EXISTS search_text TEXT;

CREATE TABLE IF NOT EXISTS people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  name_folded TEXT NOT NULL,
  thumb_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS movie_cast (
  movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
  person_id INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK(kind IN ('actor','director')),
  position INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(movie_id,person_id,kind)
);

CREATE INDEX IF NOT EXISTS movie_cast_person_kind_idx ON movie_cast(person_id,kind);
CREATE INDEX IF NOT EXISTS people_name_folded_idx ON people(name_folded);

-- FK không có index: JOIN và ON DELETE CASCADE phải seq scan.
CREATE INDEX IF NOT EXISTS episodes_movie_idx ON episodes(movie_id);
CREATE INDEX IF NOT EXISTS favorites_movie_idx ON favorites(movie_id);
CREATE INDEX IF NOT EXISTS watch_progress_movie_idx ON watch_progress(movie_id);
CREATE INDEX IF NOT EXISTS movie_genres_name_idx ON movie_genres(name);
CREATE INDEX IF NOT EXISTS movie_countries_name_idx ON movie_countries(name);
CREATE INDEX IF NOT EXISTS movies_year_idx ON movies(year DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS movies_rating_idx ON movies(rating DESC NULLS LAST);

-- Tìm chuỗi con. Thiếu pg_trgm thì ILIKE vẫn đúng, chỉ chậm hơn.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS movies_search_trgm_idx ON movies USING gin (search_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS people_name_trgm_idx ON people USING gin (name_folded gin_trgm_ops);
