import postgres from 'postgres';
import type { Episode, Movie, Person } from './types.js';
import { fold, movieSearchText, slugifyName } from './text.js';

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('DATABASE_URL is required');

export const sql = postgres(databaseUrl, {
  max: Number(process.env.DATABASE_POOL_SIZE ?? 10), idle_timeout: 20, connect_timeout: 15,
  prepare: false, ssl: process.env.DATABASE_SSL === 'false' ? false : 'require'
});

const castAgg = (kind: 'actor' | 'director') =>
  `COALESCE((SELECT json_agg(p.name ORDER BY c.position,p.name) FROM movie_cast c JOIN people p ON p.id=c.person_id WHERE c.movie_id=m.id AND c.kind='${kind}'), '[]'::json)`;

const movieSelect = `
  m.id, m.provider, m.provider_id, m.slug, m.name, m.origin_name, m.description, m.type, m.status,
  m.year, m.duration, m.quality, m.language, m.poster_url, m.thumb_url, m.trailer_url,
  m.rating, m.view_count, m.tmdb_id, m.imdb_id,
  COALESCE((SELECT json_agg(mg.name ORDER BY mg.name) FROM movie_genres mg WHERE mg.movie_id=m.id), '[]'::json) AS genres,
  COALESCE((SELECT json_agg(mc.name ORDER BY mc.name) FROM movie_countries mc WHERE mc.movie_id=m.id), '[]'::json) AS countries,
  ${castAgg('actor')} AS actors,
  ${castAgg('director')} AS directors,
  COALESCE((SELECT json_agg(json_build_object('name',p.name,'slug',p.slug,'thumbUrl',p.thumb_url,'kind',c.kind) ORDER BY c.kind,c.position,p.name)
    FROM movie_cast c JOIN people p ON p.id=c.person_id WHERE c.movie_id=m.id), '[]'::json) AS cast_list`;


export async function initDatabase() {
  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS movies (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider TEXT NOT NULL, provider_id TEXT,
      slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, origin_name TEXT, description TEXT,
      type TEXT NOT NULL DEFAULT 'single', status TEXT, year INTEGER, duration TEXT, quality TEXT,
      language TEXT, poster_url TEXT, thumb_url TEXT, trailer_url TEXT, rating DOUBLE PRECISION,
      view_count INTEGER NOT NULL DEFAULT 0, tmdb_id TEXT, imdb_id TEXT, raw_json JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(provider,provider_id)
    );
    CREATE TABLE IF NOT EXISTS movie_genres (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(movie_id,name));
    CREATE TABLE IF NOT EXISTS movie_countries (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(movie_id,name));
    CREATE TABLE IF NOT EXISTS movie_people (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('actor','director')), name TEXT NOT NULL, UNIQUE(movie_id,kind,name));
    CREATE TABLE IF NOT EXISTS episodes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      server_name TEXT NOT NULL, name TEXT NOT NULL, episode_number INTEGER, embed_url TEXT NOT NULL, m3u8_url TEXT,
      UNIQUE(movie_id,server_name,name)
    );
    CREATE TABLE IF NOT EXISTS watch_progress (
      device_id TEXT NOT NULL, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      episode_id INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE, position_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
      duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0, completed BOOLEAN NOT NULL DEFAULT FALSE,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(device_id,episode_id)
    );
    CREATE TABLE IF NOT EXISTS favorites (
      device_id TEXT NOT NULL, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(device_id,movie_id)
    );
    CREATE TABLE IF NOT EXISTS sync_state (
      id INTEGER PRIMARY KEY CHECK(id=1), status TEXT NOT NULL DEFAULT 'idle', page INTEGER NOT NULL DEFAULT 0,
      total_pages INTEGER NOT NULL DEFAULT 0, processed INTEGER NOT NULL DEFAULT 0, error TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    INSERT INTO sync_state(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
    CREATE INDEX IF NOT EXISTS movies_updated_at_idx ON movies(updated_at DESC);
    CREATE INDEX IF NOT EXISTS movie_people_kind_name_idx ON movie_people(kind,name);
    CREATE INDEX IF NOT EXISTS watch_progress_device_updated_idx ON watch_progress(device_id,updated_at DESC);
  `);
  await migrateSchema();
}

/**
 * Phần schema thêm sau bản init đầu tiên. Tách riêng để dễ đọc và để chỗ nào
 * có thể thất bại (index trgm cần extension) thì không làm chết cả boot.
 */
async function migrateSchema() {
  await sql.unsafe(`
    -- Tên đã bỏ dấu, lưu sẵn để tìm kiếm "nguoi nhen" ra "Người Nhện".
    ALTER TABLE movies ADD COLUMN IF NOT EXISTS search_text TEXT;

    -- Người (diễn viên/đạo diễn) là thực thể riêng, có slug để đặt vào URL.
    CREATE TABLE IF NOT EXISTS people (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, name_folded TEXT NOT NULL,
      thumb_url TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS movie_cast (
      movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      person_id INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
      kind TEXT NOT NULL CHECK(kind IN ('actor','director')),
      position INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY(movie_id,person_id,kind)
    );

    CREATE INDEX IF NOT EXISTS movie_cast_person_kind_idx ON movie_cast(person_id,kind);
    CREATE INDEX IF NOT EXISTS people_name_folded_idx ON people(name_folded);
    -- FK thiếu index: JOIN và ON DELETE CASCADE đều phải seq scan nếu không có.
    CREATE INDEX IF NOT EXISTS episodes_movie_idx ON episodes(movie_id);
    CREATE INDEX IF NOT EXISTS favorites_movie_idx ON favorites(movie_id);
    CREATE INDEX IF NOT EXISTS watch_progress_movie_idx ON watch_progress(movie_id);
    CREATE INDEX IF NOT EXISTS movie_genres_name_idx ON movie_genres(name);
    CREATE INDEX IF NOT EXISTS movie_countries_name_idx ON movie_countries(name);
    CREATE INDEX IF NOT EXISTS movies_year_idx ON movies(year DESC NULLS LAST);
    CREATE INDEX IF NOT EXISTS movies_rating_idx ON movies(rating DESC NULLS LAST);
  `);

  // pg_trgm cho tìm kiếm chuỗi con. Thiếu extension thì bỏ qua: ILIKE trên
  // search_text vẫn cho kết quả đúng, chỉ chậm hơn — với catalog vài nghìn phim
  // thì không đáng để làm sập boot.
  try {
    await sql.unsafe(`
      CREATE EXTENSION IF NOT EXISTS pg_trgm;
      CREATE INDEX IF NOT EXISTS movies_search_trgm_idx ON movies USING gin (search_text gin_trgm_ops);
      CREATE INDEX IF NOT EXISTS people_name_trgm_idx ON people USING gin (name_folded gin_trgm_ops);
    `);
  } catch (error) {
    console.warn('pg_trgm không khả dụng, tìm kiếm sẽ dùng ILIKE thuần:', (error as Error).message);
  }

  await backfill();
}

/** Lấp dữ liệu cho cột/bảng mới từ dữ liệu cũ. Idempotent, chạy mỗi lần boot. */
async function backfill() {
  const stale = await sql<{ id: number; name: string; origin_name: string | null; slug: string }[]>`
    SELECT id,name,origin_name,slug FROM movies WHERE search_text IS NULL LIMIT 5000`;
  for (const row of stale) {
    await sql`UPDATE movies SET search_text=${movieSearchText(row.name, row.origin_name, row.slug)} WHERE id=${row.id}`;
  }

  // movie_people (bảng cũ, chỉ có tên phẳng) -> people + movie_cast
  const legacy = await sql<{ movie_id: number; kind: string; name: string }[]>`
    SELECT mp.movie_id,mp.kind,mp.name FROM movie_people mp
    WHERE NOT EXISTS (SELECT 1 FROM movie_cast c WHERE c.movie_id=mp.movie_id AND c.kind=mp.kind)
    LIMIT 20000`;
  if (legacy.length) {
    const byMovie = new Map<number, { actor: string[]; director: string[] }>();
    for (const row of legacy) {
      const entry = byMovie.get(row.movie_id) ?? { actor: [], director: [] };
      if (row.kind === 'actor' || row.kind === 'director') entry[row.kind].push(row.name);
      byMovie.set(row.movie_id, entry);
    }
    for (const [movieId, entry] of byMovie) {
      await sql.begin((tx) => replaceCast(tx, movieId, entry.actor, entry.director) as any);
    }
    console.log(`Backfill: đã chuyển ${byMovie.size} phim từ movie_people sang people/movie_cast`);
  }
}


const scalar = (value: unknown) => value == null ? null : String(value);
const list = (value: unknown): string[] => Array.isArray(value)
  ? value.map((item) => typeof item === 'string' ? item : String((item as { name?: unknown })?.name ?? '')).filter(Boolean)
  : [];

function mapMovie(row: any): Movie {
  return {
    id: row.id, provider: row.provider, providerId: row.provider_id, slug: row.slug, name: row.name, originName: row.origin_name,
    description: row.description, type: row.type, status: row.status, year: row.year, duration: row.duration,
    quality: row.quality, language: row.language, posterUrl: row.poster_url, thumbUrl: row.thumb_url,
    trailerUrl: row.trailer_url, rating: row.rating, viewCount: row.view_count, tmdbId: row.tmdb_id,
    imdbId: row.imdb_id, genres: row.genres ?? [], countries: row.countries ?? [], actors: row.actors ?? [],
    directors: row.directors ?? [], cast: row.cast_list ?? []
  };
}

/**
 * `sql` bên trong một transaction. Bỏ trống tham số generic để lấy mặc định của
 * thư viện (bảng kiểu tuỳ biến — mình không khai báo cái nào).
 */
type Executor = postgres.TransactionSql;

/** Ghi tên phẳng vào bảng nối 1 lượt thay vì 1 INSERT/tên. */
async function replaceNames(tx: Executor, table: 'movie_genres' | 'movie_countries', movieId: number, names: string[]) {
  await tx.unsafe(`DELETE FROM ${table} WHERE movie_id=$1`, [movieId]);
  const unique = [...new Set(names.map((name) => name.trim()).filter(Boolean))];
  if (!unique.length) return;
  await tx.unsafe(
    `INSERT INTO ${table}(movie_id,name) SELECT $1,n FROM unnest($2::text[]) AS n ON CONFLICT DO NOTHING`,
    [movieId, unique as any]
  );
}

/**
 * Dedupe người theo tên đã bỏ dấu, upsert vào `people` rồi gắn vào `movie_cast`.
 * Toàn bộ chỉ 3 câu lệnh, không phụ thuộc số lượng diễn viên.
 */
async function replaceCast(tx: Executor, movieId: number, actors: string[], directors: string[]) {
  await tx`DELETE FROM movie_cast WHERE movie_id=${movieId}`;

  const entries: { slug: string; name: string; folded: string; kind: 'actor' | 'director'; position: number }[] = [];
  const seen = new Set<string>();
  for (const [kind, names] of [['actor', actors], ['director', directors]] as const) {
    let position = 0;
    for (const raw of names) {
      const name = String(raw ?? '').trim();
      const slug = slugifyName(name);
      if (!name || !slug) continue;
      const key = `${kind}:${slug}`;
      if (seen.has(key)) continue;
      seen.add(key);
      entries.push({ slug, name, folded: fold(name), kind, position: position++ });
    }
  }
  if (!entries.length) return;

  const unique = [...new Map(entries.map((entry) => [entry.slug, entry])).values()];
  const people = await tx<{ id: number; slug: string }[]>`
    INSERT INTO people(slug,name,name_folded)
    SELECT * FROM unnest(${unique.map((e) => e.slug)}::text[], ${unique.map((e) => e.name)}::text[], ${unique.map((e) => e.folded)}::text[])
    ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name, name_folded=EXCLUDED.name_folded, updated_at=NOW()
    RETURNING id,slug`;

  const idBySlug = new Map(people.map((row) => [row.slug, row.id]));
  const rows = entries
    .map((entry) => ({ movie_id: movieId, person_id: idBySlug.get(entry.slug), kind: entry.kind, position: entry.position }))
    .filter((row) => row.person_id != null) as { movie_id: number; person_id: number; kind: string; position: number }[];
  if (rows.length) await tx`INSERT INTO movie_cast ${tx(rows, 'movie_id', 'person_id', 'kind', 'position')} ON CONFLICT DO NOTHING`;
}

export async function upsertMovie(input: any): Promise<number> {
  const movie = input.movie ?? input; const tmdb = movie.tmdb ?? {}; const imdb = movie.imdb ?? {};
  const name = movie.name ?? movie.origin_name ?? movie.slug;
  return sql.begin(async (tx) => {
    const rows = await tx`
      INSERT INTO movies(provider,provider_id,slug,name,origin_name,description,type,status,year,duration,quality,language,poster_url,thumb_url,trailer_url,rating,view_count,tmdb_id,imdb_id,raw_json,search_text,updated_at)
      VALUES(${movie.provider ?? 'vsmov'},${scalar(movie.providerId ?? movie._id)},${movie.slug},${name},${movie.origin_name ?? null},${movie.content ?? movie.description ?? null},${movie.type ?? 'single'},${movie.status ?? null},${Number(movie.year ?? 0) || null},${movie.time ?? movie.duration ?? null},${movie.quality ?? null},${movie.lang ?? movie.language ?? null},${typeof (movie.poster_url ?? movie.posterUrl) === 'string' ? (movie.poster_url ?? movie.posterUrl) : null},${typeof (movie.thumb_url ?? movie.thumbUrl) === 'string' ? (movie.thumb_url ?? movie.thumbUrl) : null},${movie.trailer_url ?? movie.trailerUrl ?? null},${Number(tmdb.vote_average ?? movie.rating ?? 0) || null},${Number(movie.view ?? movie.viewCount ?? 0)},${scalar(tmdb.id ?? movie.tmdbId)},${scalar(imdb.id ?? movie.imdbId)},${tx.json(movie)},${movieSearchText(name, movie.origin_name, movie.slug)},NOW())
      ON CONFLICT(slug) DO UPDATE SET provider=EXCLUDED.provider,provider_id=EXCLUDED.provider_id,name=EXCLUDED.name,origin_name=EXCLUDED.origin_name,
        description=EXCLUDED.description,type=EXCLUDED.type,status=EXCLUDED.status,year=EXCLUDED.year,duration=EXCLUDED.duration,
        quality=EXCLUDED.quality,language=EXCLUDED.language,poster_url=EXCLUDED.poster_url,thumb_url=EXCLUDED.thumb_url,
        trailer_url=EXCLUDED.trailer_url,rating=EXCLUDED.rating,view_count=EXCLUDED.view_count,tmdb_id=EXCLUDED.tmdb_id,
        imdb_id=EXCLUDED.imdb_id,raw_json=EXCLUDED.raw_json,search_text=EXCLUDED.search_text,updated_at=NOW() RETURNING id`;
    const movieId = rows[0].id as number;
    await replaceNames(tx, 'movie_genres', movieId, list(movie.category ?? movie.genres));
    await replaceNames(tx, 'movie_countries', movieId, list(movie.country ?? movie.countries));
    await replaceCast(tx, movieId, list(movie.actor ?? movie.actors), list(movie.director ?? movie.directors));
    return movieId;
  });
}

export async function upsertEpisodes(movieId: number, groups: any[] = []) {
  const rows: { movie_id: number; server_name: string; name: string; episode_number: number | null; embed_url: string; m3u8_url: string | null }[] = [];
  const seen = new Set<string>();
  for (const group of groups) for (const episode of group.server_data ?? []) {
    if (!episode.link_embed) continue;
    const serverName = String(group.server_name ?? 'Default');
    const name = String(episode.name ?? episode.filename ?? 'Full');
    const key = `${serverName}|${name}`;
    if (seen.has(key)) continue; // trùng khoá UNIQUE thì INSERT nhiều dòng sẽ nổ
    seen.add(key);
    const number = Number.parseInt(String(episode.name ?? '').replace(/\D/g, ''), 10);
    rows.push({
      movie_id: movieId, server_name: serverName, name,
      episode_number: Number.isFinite(number) ? number : null,
      embed_url: String(episode.link_embed), m3u8_url: episode.link_m3u8 ?? null
    });
  }
  // Một series 100 tập trước đây là 100 round-trip; giờ là 2 câu lệnh.
  await sql.begin(async (tx) => {
    await tx`DELETE FROM episodes WHERE movie_id=${movieId}`;
    if (rows.length) await tx`INSERT INTO episodes ${tx(rows, 'movie_id', 'server_name', 'name', 'episode_number', 'embed_url', 'm3u8_url')}`;
  });
}

export async function getMovie(idOrSlug: string, withEpisodes = false): Promise<Movie | null> {
  // Tách nhánh thay vì `slug=$1 OR id::text=$1`: cách cũ làm Postgres bỏ index UNIQUE(slug).
  const numeric = /^\d+$/.test(idOrSlug);
  const rows = numeric
    ? await sql.unsafe(`SELECT ${movieSelect} FROM movies m WHERE m.id=$1 LIMIT 1`, [Number(idOrSlug)])
    : await sql.unsafe(`SELECT ${movieSelect} FROM movies m WHERE m.slug=$1 LIMIT 1`, [idOrSlug]);
  if (!rows.length) return null;
  const movie = mapMovie(rows[0]);
  if (withEpisodes) movie.episodes = await sql<Episode[]>`
    SELECT id,movie_id AS "movieId",server_name AS "serverName",name,episode_number AS "episodeNumber",embed_url AS "embedUrl",m3u8_url AS "m3u8Url"
    FROM episodes WHERE movie_id=${movie.id} ORDER BY server_name,COALESCE(episode_number,9999),id`;
  return movie;
}

export interface MovieQuery {
  q?: string;
  genre?: string;
  country?: string;
  year?: number;
  type?: string;
  /** slug người trong bảng `people` — lọc phim theo diễn viên hoặc đạo diễn. */
  person?: string;
  personKind?: 'actor' | 'director';
  page: number;
  limit: number;
  sort?: string;
}

const sortClauses: Record<string, string> = {
  rating: 'm.rating DESC NULLS LAST,m.updated_at DESC',
  year: 'm.year DESC NULLS LAST,m.updated_at DESC',
  name: 'm.name ASC',
  views: 'm.view_count DESC,m.updated_at DESC',
  recent: 'm.updated_at DESC'
};

export async function listMovies(params: MovieQuery) {
  // fold() ở đây phải khớp với search_text đã lưu, nếu không sẽ không ra kết quả.
  const search = params.q ? `%${fold(params.q)}%` : null;
  const offset = (params.page - 1) * params.limit;
  const args = [
    search, params.genre ?? null, params.country ?? null, params.year ?? null,
    params.type ?? null, params.person ?? null, params.personKind ?? null
  ];
  const where = `
    ($1::text IS NULL OR m.search_text ILIKE $1)
    AND ($2::text IS NULL OR EXISTS(SELECT 1 FROM movie_genres mg WHERE mg.movie_id=m.id AND mg.name=$2))
    AND ($3::text IS NULL OR EXISTS(SELECT 1 FROM movie_countries mc WHERE mc.movie_id=m.id AND mc.name=$3))
    AND ($4::int IS NULL OR m.year=$4)
    AND ($5::text IS NULL OR m.type=$5)
    AND ($6::text IS NULL OR EXISTS(
      SELECT 1 FROM movie_cast c JOIN people p ON p.id=c.person_id
      WHERE c.movie_id=m.id AND p.slug=$6 AND ($7::text IS NULL OR c.kind=$7)))`;
  const order = sortClauses[params.sort ?? ''] ?? sortClauses.recent;
  const countRows = await sql.unsafe(`SELECT COUNT(*)::int AS count FROM movies m WHERE ${where}`, args as any[]);
  const rows = await sql.unsafe(
    `SELECT ${movieSelect} FROM movies m WHERE ${where} ORDER BY ${order} LIMIT $8 OFFSET $9`,
    [...args, params.limit, offset] as any[]
  );
  const totalItems = countRows[0].count as number;
  return {
    items: rows.map(mapMovie),
    pagination: { totalItems, totalPages: Math.max(1, Math.ceil(totalItems / params.limit)), currentPage: params.page, totalItemsPerPage: params.limit }
  };
}

export async function getEpisodes(episodeId: number) {
  const rows = await sql<Episode[]>`SELECT id,movie_id AS "movieId",server_name AS "serverName",name,episode_number AS "episodeNumber",embed_url AS "embedUrl",m3u8_url AS "m3u8Url" FROM episodes WHERE id=${episodeId}`;
  return rows[0];
}

export async function saveProgress(deviceId: string, episodeId: number, position: number, duration: number, completed: boolean) {
  const episode = await getEpisodes(episodeId); if (!episode) return false;
  await sql`INSERT INTO watch_progress(device_id,movie_id,episode_id,position_seconds,duration_seconds,completed,updated_at)
    VALUES(${deviceId},${episode.movieId},${episodeId},${position},${duration},${completed},NOW())
    ON CONFLICT(device_id,episode_id) DO UPDATE SET position_seconds=EXCLUDED.position_seconds,duration_seconds=EXCLUDED.duration_seconds,completed=EXCLUDED.completed,updated_at=NOW()`;
  return true;
}

export async function getContinue(deviceId: string) {
  return sql`SELECT wp.*,m.slug,m.name,m.thumb_url AS "thumbUrl",e.name AS "episodeName" FROM watch_progress wp JOIN movies m ON m.id=wp.movie_id JOIN episodes e ON e.id=wp.episode_id WHERE wp.device_id=${deviceId} AND wp.completed=FALSE ORDER BY wp.updated_at DESC LIMIT 12`;
}
export async function toggleFavorite(deviceId: string, movieId: number, enabled: boolean) {
  if (enabled) await sql`INSERT INTO favorites(device_id,movie_id) VALUES(${deviceId},${movieId}) ON CONFLICT DO NOTHING`;
  else await sql`DELETE FROM favorites WHERE device_id=${deviceId} AND movie_id=${movieId}`;
}
export async function isFavorite(deviceId: string, movieId: number) { return (await sql`SELECT 1 FROM favorites WHERE device_id=${deviceId} AND movie_id=${movieId} LIMIT 1`).length > 0; }
export async function listFavorites(deviceId: string, limit = 200) {
  const rows = await sql.unsafe(
    `SELECT ${movieSelect} FROM favorites f JOIN movies m ON m.id=f.movie_id WHERE f.device_id=$1 ORDER BY f.created_at DESC LIMIT $2`,
    [deviceId, limit]
  );
  return rows.map(mapMovie);
}

/**
 * Danh sách người, sắp theo số phim giảm dần (người xuất hiện nhiều nằm trước —
 * hữu ích hơn sắp theo alphabet). `q` tìm không dấu trên `name_folded`.
 */
export async function listPeople(params: { q?: string; kind?: 'actor' | 'director'; page: number; limit: number }) {
  const search = params.q ? `%${fold(params.q)}%` : null;
  const offset = (params.page - 1) * params.limit;
  const args = [search, params.kind ?? null];
  const where = `
    ($1::text IS NULL OR p.name_folded ILIKE $1)
    AND EXISTS(SELECT 1 FROM movie_cast c WHERE c.person_id=p.id AND ($2::text IS NULL OR c.kind=$2))`;
  const countRows = await sql.unsafe(`SELECT COUNT(*)::int AS count FROM people p WHERE ${where}`, args as any[]);
  const rows = await sql.unsafe(`
    SELECT p.id,p.name,p.slug,p.thumb_url AS "thumbUrl",
      (SELECT COUNT(*)::int FROM movie_cast c WHERE c.person_id=p.id AND ($2::text IS NULL OR c.kind=$2)) AS "movieCount"
    FROM people p WHERE ${where}
    ORDER BY "movieCount" DESC,p.name ASC LIMIT $3 OFFSET $4`, [...args, params.limit, offset] as any[]);
  const totalItems = countRows[0].count as number;
  return {
    items: rows as unknown as Person[],
    pagination: { totalItems, totalPages: Math.max(1, Math.ceil(totalItems / params.limit)), currentPage: params.page, totalItemsPerPage: params.limit }
  };
}

/** Chi tiết một người + vai trò của họ (diễn viên, đạo diễn, hoặc cả hai). */
export async function getPerson(slug: string): Promise<(Person & { kinds: string[] }) | null> {
  const rows = await sql`
    SELECT p.id,p.name,p.slug,p.thumb_url AS "thumbUrl",
      (SELECT COUNT(*)::int FROM movie_cast c WHERE c.person_id=p.id) AS "movieCount",
      COALESCE((SELECT json_agg(DISTINCT c.kind) FROM movie_cast c WHERE c.person_id=p.id), '[]'::json) AS kinds
    FROM people p WHERE p.slug=${slug} LIMIT 1`;
  return (rows[0] as any) ?? null;
}

/** Ảnh diễn viên chỉ có ở provider, ghép vào bảng people theo tên đã bỏ dấu. */
export async function updatePeopleThumbs(entries: { name: string; thumbUrl: string | null }[]) {
  const usable = entries.filter((entry) => entry.thumbUrl && entry.name);
  if (!usable.length) return 0;
  const result = await sql`
    UPDATE people SET thumb_url=v.thumb_url, updated_at=NOW()
    FROM (SELECT * FROM unnest(${usable.map((e) => fold(e.name))}::text[], ${usable.map((e) => e.thumbUrl!)}::text[]) AS t(name_folded,thumb_url)) AS v
    WHERE people.name_folded=v.name_folded AND people.thumb_url IS DISTINCT FROM v.thumb_url`;
  return result.count;
}

/** Taxonomy dựng từ DB, dùng khi provider chết. */
export async function listGenresFromDb() {
  return sql`SELECT name,COUNT(*)::int AS count FROM movie_genres GROUP BY name ORDER BY count DESC,name`;
}
export async function listCountriesFromDb() {
  return sql`SELECT name,COUNT(*)::int AS count FROM movie_countries GROUP BY name ORDER BY count DESC,name`;
}
export async function listYearsFromDb() {
  return sql`SELECT year,COUNT(*)::int AS count FROM movies WHERE year IS NOT NULL GROUP BY year ORDER BY year DESC`;
}

export async function getSyncState() {
  const rows = await sql`SELECT status,page,total_pages AS "totalPages",processed,error,updated_at AS "updatedAt" FROM sync_state WHERE id=1`;
  return rows[0];
}
const syncFields: Record<string, string> = { status: 'status', page: 'page', total_pages: 'total_pages', processed: 'processed', error: 'error' };
export async function setSyncState(values: Record<string, unknown>) {
  const entries = Object.entries(values).filter(([key]) => syncFields[key]); if (!entries.length) return;
  const assignments = entries.map(([key], index) => `${syncFields[key]}=$${index + 1}`).join(',');
  await sql.unsafe(`UPDATE sync_state SET ${assignments},updated_at=NOW() WHERE id=1`, entries.map(([, value]) => value) as any[]);
}
export async function closeDatabase() { await sql.end({ timeout: 5 }); }
