import postgres from 'postgres';
import type { Episode, Movie } from './types.js';

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('DATABASE_URL is required');

export const sql = postgres(databaseUrl, {
  max: Number(process.env.DATABASE_POOL_SIZE ?? 10), idle_timeout: 20, connect_timeout: 15,
  prepare: false, ssl: process.env.DATABASE_SSL === 'false' ? false : 'require'
});

const movieSelect = `
  m.id, m.provider, m.provider_id, m.slug, m.name, m.origin_name, m.description, m.type, m.status,
  m.year, m.duration, m.quality, m.language, m.poster_url, m.thumb_url, m.trailer_url,
  m.rating, m.view_count, m.tmdb_id, m.imdb_id,
  COALESCE((SELECT json_agg(mg.name ORDER BY mg.name) FROM movie_genres mg WHERE mg.movie_id=m.id), '[]'::json) AS genres,
  COALESCE((SELECT json_agg(mc.name ORDER BY mc.name) FROM movie_countries mc WHERE mc.movie_id=m.id), '[]'::json) AS countries,
  COALESCE((SELECT json_agg(mp.name ORDER BY mp.name) FROM movie_people mp WHERE mp.movie_id=m.id AND mp.kind='actor'), '[]'::json) AS actors,
  COALESCE((SELECT json_agg(mp.name ORDER BY mp.name) FROM movie_people mp WHERE mp.movie_id=m.id AND mp.kind='director'), '[]'::json) AS directors`;

export async function initDatabase() {
  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS movies (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider TEXT NOT NULL, provider_id TEXT,
      slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, origin_name TEXT, description TEXT,
      type TEXT NOT NULL DEFAULT 'single', status TEXT, year INTEGER, duration TEXT, quality TEXT,
      language TEXT, poster_url TEXT, thumb_url TEXT, trailer_url TEXT, rating DOUBLE PRECISION,
      view_count INTEGER NOT NULL DEFAULT 0, tmdb_id TEXT, imdb_id TEXT, raw_json JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(provider,provider_id)
    );
    CREATE TABLE IF NOT EXISTS movie_genres (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(movie_id,name));
    CREATE TABLE IF NOT EXISTS movie_countries (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, name TEXT NOT NULL, UNIQUE(movie_id,name));
    CREATE TABLE IF NOT EXISTS movie_people (movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('actor','director')), name TEXT NOT NULL, UNIQUE(movie_id,kind,name));
    CREATE TABLE IF NOT EXISTS episodes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      server_name TEXT NOT NULL, name TEXT NOT NULL, episode_number INTEGER, embed_url TEXT NOT NULL, m3u8_url TEXT,
      UNIQUE(movie_id,server_name,name)
    );
    CREATE TABLE IF NOT EXISTS watch_progress (
      device_id TEXT NOT NULL, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      episode_id INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE, position_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
      duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0, completed BOOLEAN NOT NULL DEFAULT FALSE,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(device_id,episode_id)
    );
    CREATE TABLE IF NOT EXISTS favorites (
      device_id TEXT NOT NULL, movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(device_id,movie_id)
    );
    CREATE TABLE IF NOT EXISTS sync_state (
      id INTEGER PRIMARY KEY CHECK(id=1), status TEXT NOT NULL DEFAULT 'idle', page INTEGER NOT NULL DEFAULT 0,
      total_pages INTEGER NOT NULL DEFAULT 0, processed INTEGER NOT NULL DEFAULT 0, error TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    INSERT INTO sync_state(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
    CREATE INDEX IF NOT EXISTS movies_updated_at_idx ON movies(updated_at DESC);
    CREATE INDEX IF NOT EXISTS movie_people_kind_name_idx ON movie_people(kind,name);
    CREATE INDEX IF NOT EXISTS watch_progress_device_updated_idx ON watch_progress(device_id,updated_at DESC);
  `);
}

const scalar = (value: unknown) => value == null ? null : String(value);
const list = (value: unknown): string[] => Array.isArray(value)
  ? value.map((item) => typeof item === 'string' ? item : String((item as { name?: unknown })?.name ?? '')).filter(Boolean)
  : [];

function mapMovie(row: any): Movie {
  return {
    id: row.id, provider: row.provider, providerId: row.provider_id, slug: row.slug, name: row.name, originName: row.origin_name,
    description: row.description, type: row.type, status: row.status, year: row.year, duration: row.duration,
    quality: row.quality, language: row.language, posterUrl: row.poster_url, thumbUrl: row.thumb_url,
    trailerUrl: row.trailer_url, rating: row.rating, viewCount: row.view_count, tmdbId: row.tmdb_id,
    imdbId: row.imdb_id, genres: row.genres ?? [], countries: row.countries ?? [], actors: row.actors ?? [], directors: row.directors ?? []
  };
}

export async function upsertMovie(input: any): Promise<number> {
  const movie = input.movie ?? input; const tmdb = movie.tmdb ?? {}; const imdb = movie.imdb ?? {};
  return sql.begin(async (tx) => {
    const rows = await tx`
      INSERT INTO movies(provider,provider_id,slug,name,origin_name,description,type,status,year,duration,quality,language,poster_url,thumb_url,trailer_url,rating,view_count,tmdb_id,imdb_id,raw_json,updated_at)
      VALUES(${movie.provider ?? 'vsmov'},${scalar(movie.providerId ?? movie._id)},${movie.slug},${movie.name ?? movie.origin_name ?? movie.slug},${movie.origin_name ?? null},${movie.content ?? movie.description ?? null},${movie.type ?? 'single'},${movie.status ?? null},${Number(movie.year ?? 0) || null},${movie.time ?? movie.duration ?? null},${movie.quality ?? null},${movie.lang ?? movie.language ?? null},${typeof (movie.poster_url ?? movie.posterUrl) === 'string' ? (movie.poster_url ?? movie.posterUrl) : null},${typeof (movie.thumb_url ?? movie.thumbUrl) === 'string' ? (movie.thumb_url ?? movie.thumbUrl) : null},${movie.trailer_url ?? movie.trailerUrl ?? null},${Number(tmdb.vote_average ?? movie.rating ?? 0) || null},${Number(movie.view ?? movie.viewCount ?? 0)},${scalar(tmdb.id ?? movie.tmdbId)},${scalar(imdb.id ?? movie.imdbId)},${tx.json(movie)},NOW())
      ON CONFLICT(slug) DO UPDATE SET provider=EXCLUDED.provider,provider_id=EXCLUDED.provider_id,name=EXCLUDED.name,origin_name=EXCLUDED.origin_name,
        description=EXCLUDED.description,type=EXCLUDED.type,status=EXCLUDED.status,year=EXCLUDED.year,duration=EXCLUDED.duration,
        quality=EXCLUDED.quality,language=EXCLUDED.language,poster_url=EXCLUDED.poster_url,thumb_url=EXCLUDED.thumb_url,
        trailer_url=EXCLUDED.trailer_url,rating=EXCLUDED.rating,view_count=EXCLUDED.view_count,tmdb_id=EXCLUDED.tmdb_id,
        imdb_id=EXCLUDED.imdb_id,raw_json=EXCLUDED.raw_json,updated_at=NOW() RETURNING id`;
    const movieId = rows[0].id as number;
    await tx`DELETE FROM movie_genres WHERE movie_id=${movieId}`;
    await tx`DELETE FROM movie_countries WHERE movie_id=${movieId}`;
    await tx`DELETE FROM movie_people WHERE movie_id=${movieId}`;
    for (const name of list(movie.category)) await tx`INSERT INTO movie_genres(movie_id,name) VALUES(${movieId},${name}) ON CONFLICT DO NOTHING`;
    for (const name of list(movie.country)) await tx`INSERT INTO movie_countries(movie_id,name) VALUES(${movieId},${name}) ON CONFLICT DO NOTHING`;
    for (const name of list(movie.actor)) await tx`INSERT INTO movie_people(movie_id,kind,name) VALUES(${movieId},'actor',${name}) ON CONFLICT DO NOTHING`;
    for (const name of list(movie.director)) await tx`INSERT INTO movie_people(movie_id,kind,name) VALUES(${movieId},'director',${name}) ON CONFLICT DO NOTHING`;
    return movieId;
  });
}

export async function upsertEpisodes(movieId: number, groups: any[] = []) {
  await sql.begin(async (tx) => {
    await tx`DELETE FROM episodes WHERE movie_id=${movieId}`;
    for (const group of groups) for (const episode of group.server_data ?? []) {
      if (!episode.link_embed) continue;
      const number = Number.parseInt(String(episode.name ?? '').replace(/\D/g, ''), 10);
      await tx`INSERT INTO episodes(movie_id,server_name,name,episode_number,embed_url,m3u8_url)
        VALUES(${movieId},${group.server_name ?? 'Default'},${episode.name ?? episode.filename ?? 'Full'},${Number.isFinite(number) ? number : null},${episode.link_embed},${episode.link_m3u8 ?? null})
        ON CONFLICT(movie_id,server_name,name) DO UPDATE SET episode_number=EXCLUDED.episode_number,embed_url=EXCLUDED.embed_url,m3u8_url=EXCLUDED.m3u8_url`;
    }
  });
}

export async function getMovie(idOrSlug: string, withEpisodes = false): Promise<Movie | null> {
  const rows = await sql.unsafe(`SELECT ${movieSelect} FROM movies m WHERE m.slug=$1 OR m.id::text=$1 LIMIT 1`, [idOrSlug]);
  if (!rows.length) return null;
  const movie = mapMovie(rows[0]);
  if (withEpisodes) movie.episodes = await sql<Episode[]>`
    SELECT id,movie_id AS "movieId",server_name AS "serverName",name,episode_number AS "episodeNumber",embed_url AS "embedUrl",m3u8_url AS "m3u8Url"
    FROM episodes WHERE movie_id=${movie.id} ORDER BY server_name,COALESCE(episode_number,9999),id`;
  return movie;
}

export async function listMovies(params: { q?: string; genre?: string; page: number; limit: number; sort?: string }) {
  const search = params.q ? `%${params.q}%` : null; const offset = (params.page - 1) * params.limit;
  const where = `($1::text IS NULL OR m.name ILIKE $1 OR m.origin_name ILIKE $1) AND ($2::text IS NULL OR EXISTS(SELECT 1 FROM movie_genres mg WHERE mg.movie_id=m.id AND mg.name=$2))`;
  const order = params.sort === 'rating' ? 'm.rating DESC NULLS LAST,m.updated_at DESC' : 'm.updated_at DESC';
  const countRows = await sql.unsafe(`SELECT COUNT(*)::int AS count FROM movies m WHERE ${where}`, [search, params.genre ?? null]);
  const rows = await sql.unsafe(`SELECT ${movieSelect} FROM movies m WHERE ${where} ORDER BY ${order} LIMIT $3 OFFSET $4`, [search, params.genre ?? null, params.limit, offset]);
  const totalItems = countRows[0].count as number;
  return { items: rows.map(mapMovie), pagination: { totalItems, totalPages: Math.ceil(totalItems / params.limit), currentPage: params.page, totalItemsPerPage: params.limit } };
}

export async function getEpisodes(episodeId: number) {
  const rows = await sql<Episode[]>`SELECT id,movie_id AS "movieId",server_name AS "serverName",name,episode_number AS "episodeNumber",embed_url AS "embedUrl",m3u8_url AS "m3u8Url" FROM episodes WHERE id=${episodeId}`;
  return rows[0];
}

export async function saveProgress(deviceId: string, episodeId: number, position: number, duration: number, completed: boolean) {
  const episode = await getEpisodes(episodeId); if (!episode) return false;
  await sql`INSERT INTO watch_progress(device_id,movie_id,episode_id,position_seconds,duration_seconds,completed,updated_at)
    VALUES(${deviceId},${episode.movieId},${episodeId},${position},${duration},${completed},NOW())
    ON CONFLICT(device_id,episode_id) DO UPDATE SET position_seconds=EXCLUDED.position_seconds,duration_seconds=EXCLUDED.duration_seconds,completed=EXCLUDED.completed,updated_at=NOW()`;
  return true;
}

export async function getContinue(deviceId: string) {
  return sql`SELECT wp.*,m.slug,m.name,m.thumb_url AS "thumbUrl",e.name AS "episodeName" FROM watch_progress wp JOIN movies m ON m.id=wp.movie_id JOIN episodes e ON e.id=wp.episode_id WHERE wp.device_id=${deviceId} AND wp.completed=FALSE ORDER BY wp.updated_at DESC LIMIT 12`;
}
export async function toggleFavorite(deviceId: string, movieId: number, enabled: boolean) {
  if (enabled) await sql`INSERT INTO favorites(device_id,movie_id) VALUES(${deviceId},${movieId}) ON CONFLICT DO NOTHING`;
  else await sql`DELETE FROM favorites WHERE device_id=${deviceId} AND movie_id=${movieId}`;
}
export async function isFavorite(deviceId: string, movieId: number) { return (await sql`SELECT 1 FROM favorites WHERE device_id=${deviceId} AND movie_id=${movieId} LIMIT 1`).length > 0; }
export async function listFavorites(deviceId: string) {
  const rows = await sql.unsafe(`SELECT ${movieSelect} FROM favorites f JOIN movies m ON m.id=f.movie_id WHERE f.device_id=$1 ORDER BY f.created_at DESC`, [deviceId]);
  return rows.map(mapMovie);
}
export async function listActors() {
  const rows = await sql`SELECT MIN(movie_id)::int AS id,name FROM movie_people WHERE kind='actor' GROUP BY name ORDER BY name`;
  return { items: rows.map((row) => ({ id: row.id, name: row.name, slug: row.name, thumbUrl: null })) };
}
export async function getSyncState() {
  const rows = await sql`SELECT status,page,total_pages AS "totalPages",processed,error,updated_at AS "updatedAt" FROM sync_state WHERE id=1`;
  return rows[0];
}
const syncFields: Record<string, string> = { status: 'status', page: 'page', total_pages: 'total_pages', processed: 'processed', error: 'error' };
export async function setSyncState(values: Record<string, unknown>) {
  const entries = Object.entries(values).filter(([key]) => syncFields[key]); if (!entries.length) return;
  const assignments = entries.map(([key], index) => `${syncFields[key]}=$${index + 1}`).join(',');
  await sql.unsafe(`UPDATE sync_state SET ${assignments},updated_at=NOW() WHERE id=1`, entries.map(([, value]) => value) as any[]);
}
export async function closeDatabase() { await sql.end({ timeout: 5 }); }
